First try at an `fpm` build
• Added a toml manifest, according to fpm v0.9.0 documentation
  > finally should be possible to build with mpif90
  > finally the cpp preprocessor should be supported
• Added a custom response (.rsp) file, to allow defining flags
• Moved all to-be-included files in specific subdirectories
  > this would in general make the repository tidier
  > all relevant CMakeLists have been modified accordingly
  > the CMake build has been ensured to remain functional

Yet we still face nontrivial issues:
————————————————————————————————————————————————————————————————————————
fpm @release
 + which mpiexec
/usr/local/bin/mpiexec
parpack_d.f90                          failed.
[  0%] Compiling...
././src/SF_SP_LINALG/include/parpack_d.f90:59:14:

   59 |   mpi_master= Get_master_MPI(MpiComm)
      |              1
Error: Cannot convert REAL(4) to LOGICAL(4) at (1)
<ERROR> Compilation failed for object " src_SF_SP_LINALG_include_parpack_d.f90.o "
<ERROR> stopping due to failed compilation
STOP 1
————————————————————————————————————————————————————————————————————————

NOTE: my previous attempts stopped instead with SF_OPTIMIZE, so indeed
      something has changed, hopefully for the better(?)