Further investigations
• This reverts commit 503b2a55571c48f983d1bab7a78930cb727c9a5e

• This also includes explicit use statements into parpack_{c,d}

• This compiles the parpack files and gets stuck downstream

Hence the actual problem is that fpm, for some reason, cannot see
the module header, when compiling included files. Which is truly
annoying I guess.

The downstream errors with lanczos_d confirm the suspicion:
——————————————————————————————————————————————————————————————————————————————————————————————————————
fpm @debug
 + which mpiexec
/usr/local/bin/mpiexec
DVDSON.f                               done.
lanczos_d.f90                          failed.
[  0%] Compiling...
././src/SF_SP_LINALG/include/lanczos_d.f90:30:28:

   30 |   if(present(iverbose))verb=iverbose
      |                            1
Error: Cannot convert LOGICAL(4) to REAL(4) at (1)

>>>>> NOTE THAT "VERB" IS DECLARED IN THE MODULE AS LOGICAL(4)

././src/SF_SP_LINALG/include/lanczos_d.f90:39:11:

   39 |         if(verb)write(*,*)"LANCZOS_EIGH_D: random initial vector generated:"
      |           1
Error: IF clause at (1) requires a scalar LOGICAL expression
././src/SF_SP_LINALG/include/lanczos_d.f90:42:11:

   42 |         if(verb)write(*,*)"LANCZOS_EIGH_D: unitary initial vector generated:"
      |           1
Error: IF clause at (1) requires a scalar LOGICAL expression
././src/SF_SP_LINALG/include/lanczos_d.f90:56:29:

   56 |      call lanczos_iteration_d(MatVec,iter,vin,vout,a_,b_)
      |                             1
Error: Explicit interface required for 'lanczos_iteration_d' at (1): assumed-shape argument
././src/SF_SP_LINALG/include/lanczos_d.f90:65:49:

   65 |      call eigh(diag(1:Nlanc),subdiag(2:Nlanc),Ev=Z(:Nlanc,:Nlanc))
      |                                                 1
Error: Keyword argument requires explicit interface for procedure 'eigh' at (1)
././src/SF_SP_LINALG/include/lanczos_d.f90:71:14:

   71 |            if(verb)write(*,*)'iter, E0, deltaE = ',iter,diag(1),diff
      |              1
Error: IF clause at (1) requires a scalar LOGICAL expression
././src/SF_SP_LINALG/include/lanczos_d.f90:83:46:

   83 |   call eigh(diag(1:Nlanc),subdiag(2:Nlanc),Ev=Z(:Nlanc,:Nlanc))
      |                                              1
Error: Keyword argument requires explicit interface for procedure 'eigh' at (1)
././src/SF_SP_LINALG/include/lanczos_d.f90:56:29:

   56 |      call lanczos_iteration_d(MatVec,iter,vin,vout,a_,b_)
      |                             1
Error: Explicit interface required for 'lanczos_iteration_d' at (1): assumed-shape argument
././src/SF_SP_LINALG/include/lanczos_d.f90:99:5:

   99 |   if(verb)then
      |     1
Error: IF clause at (1) requires a scalar LOGICAL expression
././src/SF_SP_LINALG/include/lanczos_d.f90:147:29:

  147 |      call lanczos_iteration_d(MatVec,iter,vin,vout,a_,b_)
      |                             1
Error: Explicit interface required for 'lanczos_iteration_d' at (1): assumed-shape argument
././src/SF_SP_LINALG/include/lanczos_d.f90:83:46:

   83 |   call eigh(diag(1:Nlanc),subdiag(2:Nlanc),Ev=Z(:Nlanc,:Nlanc))
      |                                              1
Error: Keyword argument 'ev' at (1) is not in the procedure
<ERROR> Compilation failed for object " src_SF_SP_LINALG_include_lanczos_d.f90.o "
<ERROR> stopping due to failed compilation
STOP 1
——————————————————————————————————————————————————————————————————————————————————————————————————————